[project]
name = "obsidian-rag-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.0.15",
    "pyright>=1.1.403",
    "torch>=2.7.0",
    "vllm>=0.9.2",
]
