# Ruff configuration file with all default settings explicitly set

# Target Python version
target-version = "py38"

# Line length for formatting and linting
line-length = 88

# Indentation
indent-width = 4

# Files to include/exclude
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Respect gitignore
respect-gitignore = true

# Show fixes in output
show-fixes = false

# Show source code in output
show-source = false

# Output format
output-format = "text"

# Preview mode
preview = false

# Unsafe fixes
unsafe-fixes = false

# Force exclusions
force-exclude = false

# Required version
required-version = ""

# Linting configuration
[lint]
# Rules to enable (empty means use default set)
select = ["E", "F"]

# Rules to ignore
ignore = []

# Rules to fix
fixable = ["ALL"]

# Rules not to fix
unfixable = []

# Dummy variable regex
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Allow unused variables when underscore-prefixed
ignore-init-module-imports = false

# Task tags
task-tags = ["TODO", "FIXME", "XXX"]

# Typing modules
typing-modules = []

# Logger objects
logger-objects = []

# Extend per-file ignores
per-file-ignores = {}

# External dependencies
external = []

# Explicit preview rules
explicit-preview-rules = false

# Linter-specific settings
[lint.flake8-annotations]
allow-star-arg-any = false
ignore-fully-untyped = false
mypy-init-return = false
suppress-dummy-args = false
suppress-none-returning = false

[lint.flake8-bandit]
check-typed-exception = false
hardcoded-tmp-directory = ["/tmp", "/var/tmp", "/dev/shm"]

[lint.flake8-bugbear]
extend-immutable-calls = []

[lint.flake8-builtins]
builtins-ignorelist = []

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = false

[lint.flake8-errmsg]
max-string-length = 0

[lint.flake8-gettext]
extend-ignore-names = []
functions-names = ["_", "gettext", "ngettext"]

[lint.flake8-import-conventions]
aliases = {}
banned-aliases = {}
banned-from = []

[lint.flake8-pytest-style]
fixture-parentheses = true
mark-parentheses = true
parametrize-names-type = "tuple"
parametrize-values-row-type = "tuple"
parametrize-values-type = "list"
raises-extend-require-match-for = ["requests.RequestException"]
raises-require-match-for = ["requests.RequestException"]

[lint.flake8-quotes]
avoid-escape = true
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[lint.flake8-self]
extend-ignore-names = []

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"
banned-api = {}
banned-module-level-imports = []

[lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]
quote-annotations = false
runtime-evaluated-base-classes = []
runtime-evaluated-decorators = []
strict = false

[lint.flake8-unused-arguments]
ignore-variadic-names = false

[lint.isort]
case-sensitive = false
classes = []
combine-as-imports = false
constants = []
detect-same-package = true
extra-standard-library = []
force-single-line = false
force-sort-within-sections = false
force-to-top = []
force-wrap-aliases = false
from-first = false
known-first-party = []
known-local-folder = []
known-third-party = []
length-sort = false
length-sort-straight = false
lines-after-imports = -1
lines-between-sections = 1
lines-between-types = 0
no-lines-before = []
no-sections = false
order-by-type = true
relative-imports-order = "closest-to-furthest"
required-imports = []
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
single-line-exclusions = []
split-on-trailing-comma = true
variables = []

[lint.mccabe]
max-complexity = 10

[lint.pep8-naming]
classmethod-decorators = ["classmethod"]
extend-ignore-names = []
ignore-names = []
staticmethod-decorators = ["staticmethod"]

[lint.pycodestyle]
ignore-overlong-task-comments = false
max-doc-length = 0
max-line-length = 88

[lint.pydocstyle]
convention = "google"
ignore-decorators = []
property-decorators = []

[lint.pyflakes]
extend-generics = []

[lint.pylint]
allow-dunder-method-names = []
allow-magic-value-types = ["int", "str", "bytes"]
max-args = 5
max-branches = 12
max-returns = 6
max-statements = 50

[lint.pyupgrade]
keep-percent-format = false
keep-fstring-formatting = false
keep-runtime-typing = false

# Formatting configuration
[format]
# Quote style
quote-style = "double"

# Indent style
indent-style = "space"

# Skip magic trailing comma
skip-magic-trailing-comma = false

# Line ending
line-ending = "auto"

# Docstring formatting
docstring-code-format = false
docstring-code-line-length = "dynamic"

# Preview mode for formatter
preview = false
